# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.srcs/sources_1/ip/clk_50hz/clk_50hz.xci
# IP: The module: 'clk_50hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.srcs/sources_1/ip/clk_50hz/clk_50hz.xci
# IP: The module: 'clk_50hz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/git repositories/CHIP8-FPGA/Vivado/Display-Test/Display-Test.gen/sources_1/ip/clk_50hz/clk_50hz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_50hz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
