-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (win64) Build 3671981 Fri Oct 14 05:00:03 MDT 2022
-- Date        : Thu May 25 23:43:55 2023
-- Host        : DESKTOP-MATTHIJS running 64-bit major release  (build 9200)
-- Command     : write_vhdl -mode funcsim -nolib -force -file
--               D:/git/Overig/CHIP8-FPGA/Vivado/CHIP8-FPGA/CHIP8-FPGA.sim/sim_main/synth/func/xsim/chip8_cpu_tb_func_synth.vhd
-- Design      : chip8_cpu
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7a100tcsg324-1
-- --------------------------------------------------------------------------------
